### ISSUE TITLE
vagrant up fail

### ISSUE THREAD

**Issue by keyboardfann** [confluentinc/securing-kafka-blog#1]
Hello,
    I use this to test kafka only-ssl branch , but will fail..... The following are my steps.

C:>git clone https://github.com/confluentinc/securing-kafka-blog.git
Cloning into 'securing-kafka-blog'...
remote: Counting objects: 46, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 46 (delta 18), reused 46 (delta 18), pack-reused 0
Unpacking objects: 100% (46/46), done.
Checking connectivity... done.

C:>cd securing-kafka-blog

C:\securing-kafka-blog>git checkout ssl-only
Branch ssl-only set up to track remote branch ssl-only from origin.
Switched to a new branch 'ssl-only'

C:\securing-kafka-blog>
C:\securing-kafka-blog>
C:\securing-kafka-blog>ls
README.md  Vagrantfile  manifests

C:\securing-kafka-blog>vim Vagrantfile

C:\securing-kafka-blog>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puppetlabs/centos-7.2-64-puppet'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puppetlabs/centos-7.2-64-puppet' is up to date...
==> default: Setting the name of the VM: securing-kafka-blog_default_14652054434
22_69733
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/securing-kafka-blog
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Notice: Preparing to install into /etc/puppetlabs/code/environments
/production/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppetlabs/code/environments/production/modules
==> default: ��������� puppetlabs-stdlib (v4.12.0)
==> default: Notice: Preparing to install into /etc/puppetlabs/code/environments
/production/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppetlabs/code/environments/production/modules
==> default: ��������� puppetlabs-inifile (v1.5.0)
==> default: Notice: Preparing to install into /etc/puppetlabs/code/environments
/production/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppetlabs/code/environments/production/modules
==> default: ��������� puppetlabs-motd (v1.4.0)
==> default:   ��������� puppetlabs-registry (v1.1.3)
==> default:     ��������� puppetlabs-stdlib (v4.12.0)
==> default: Notice: Preparing to install into /etc/puppetlabs/code/environments
/production/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppetlabs/code/environments/production/modules
==> default: ��������� saz-ssh (v2.8.1)
==> default:   ��������� puppetlabs-concat (v2.1.0)
==> default:   ��������� puppetlabs-stdlib (v4.12.0)
==> default: Notice: Compiled catalog for kafka.example.com in environment produ
ction in 0.76 seconds
==> default: Notice: /Stage[main]/Main/Package[epel-release]/ensure: created
==> default: Notice: /Stage[main]/Main/Yumrepo[confluent]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[confluent-kafka-2.11.7]/ensure: c
reated
==> default: Notice: /Stage[main]/Main/Package[java-1.8.0-openjdk-headless]/ensu
re: created
==> default: Notice: /Stage[main]/Main/Package[haveged]/ensure: created
==> default: Notice: /Stage[main]/Main/Service[haveged]/ensure: ensure changed '
stopped' to 'running'
==> default: Notice: /Stage[main]/Main/File[/etc/security/tls]/ensure: created
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Generating a 2048 bit RSA private key
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: ...................+++
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: ................+++
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: writing new private key to 'ca-key'
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: -----
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: No value provided for Subject Attribute O, skipped
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 1: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Certificate was added to keystore
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 2: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Certificate was added to keystore
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 3: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 4: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Signature ok
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: subject=/C=GB/ST=London/L=London/O=Confluent/OU=Broker/CN=kafka.example
.com
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Getting CA Private Key
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: unable to write 'random state'
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 5: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Certificate was added to keystore
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 6: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Certificate reply was installed in keystore
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 7: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 8: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 9: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Signature ok
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: subject=/C=GB/ST=London/L=London/O=Confluent/OU=Client/CN=kafka.example
.com
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Getting CA Private Key
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: unable to write 'random state'
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 10: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: Certificate was added to keystore
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: sh: line 11: $'\r': command not found
==> default: Notice: /Stage[main]/Main/Exec[generate keystores and truststores]/
returns: keytool error: java.io.IOException: Keystore was tampered with, or pass
word was incorrect
==> default: Notice: /Stage[main]/Main/File[/var/lib/kafka]: Dependency Exec[gen
erate keystores and truststores] has failures: true
==> default: Notice: /Stage[main]/Main/File[/etc/kafka/zookeeper.properties]: De
pendency Exec[generate keystores and truststores] has failures: true
==> default: Notice: /Stage[main]/Main/File[/usr/sbin/start-zk-and-kafka]: Depen
dency Exec[generate keystores and truststores] has failures: true
==> default: Notice: /Stage[main]/Main/File[/etc/kafka/server.properties]: Depen
dency Exec[generate keystores and truststores] has failures: true
==> default: Notice: /Stage[main]/Main/File[/etc/kafka/consumer_ssl.properties]:
 Dependency Exec[generate keystores and truststores] has failures: true
==> default: Notice: /Stage[main]/Main/File[/etc/kafka/producer_ssl.properties]:
 Dependency Exec[generate keystores and truststores] has failures: true
==> default: Notice: /Stage[main]/Motd/File[/etc/motd]: Dependency Exec[generate
 keystores and truststores] has failures: true
==> default: Error: keytool -genkey -noprompt -alias kafka.example.com -keypass
test1234 -keystore /etc/security/tls/kafka.server.keystore.jks -storepass test12
34 -dname "CN=kafka.example.com, OU=Broker, O=Confluent, L=London, ST=London, C=
GB" &&
==> default: openssl req -new -x509 -keyout ca-key -out ca-cert -days 365 -passo
ut pass:test1234 -subj "/CN=ca.example.com/O=/L=London/ST=London/C=GB" &&
==> default: keytool -keystore /etc/security/tls/kafka.server.truststore.jks -al
ias CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.truststore.jks -al
ias CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.server.keystore.jks -alia
s kafka.example.com -certreq -file server-cert-file -noprompt -storepass test123
4 &&
==> default: openssl x509 -req -CA ca-cert -CAkey ca-key -in server-cert-file -o
ut server-cert-signed -days 365 -CAcreateserial -passin pass:test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.server.keystore.jks -alia
s CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.server.keystore.jks -alia
s kafka.example.com -import -file server-cert-signed -noprompt -storepass test12
34 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s kafka.example.com -dname "CN=kafka.example.com, OU=Client, O=Confluent, L=Lond
on, ST=London, C=GB" -validity 365 -genkey -noprompt -storepass test1234 -keypas
s test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s kafka.example.com -certreq -file client-cert-file -noprompt -storepass test123
4 &&
==> default: openssl x509 -req -CA ca-cert -CAkey ca-key -in client-cert-file -o
ut client-cert-signed -days 365 -CAcreateserial -passin pass:test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s kafka.example.com -import -file client-cert-signed -noprompt -storepass test12
34
==> default:  returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[generate keystores and truststores]/r
eturns: change from notrun to 0 failed: keytool -genkey -noprompt -alias kafka.e
xample.com -keypass test1234 -keystore /etc/security/tls/kafka.server.keystore.j
ks -storepass test1234 -dname "CN=kafka.example.com, OU=Broker, O=Confluent, L=L
ondon, ST=London, C=GB" &&
==> default: openssl req -new -x509 -keyout ca-key -out ca-cert -days 365 -passo
ut pass:test1234 -subj "/CN=ca.example.com/O=/L=London/ST=London/C=GB" &&
==> default: keytool -keystore /etc/security/tls/kafka.server.truststore.jks -al
ias CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.truststore.jks -al
ias CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.server.keystore.jks -alia
s kafka.example.com -certreq -file server-cert-file -noprompt -storepass test123
4 &&
==> default: openssl x509 -req -CA ca-cert -CAkey ca-key -in server-cert-file -o
ut server-cert-signed -days 365 -CAcreateserial -passin pass:test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.server.keystore.jks -alia
s CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.server.keystore.jks -alia
s kafka.example.com -import -file server-cert-signed -noprompt -storepass test12
34 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s kafka.example.com -dname "CN=kafka.example.com, OU=Client, O=Confluent, L=Lond
on, ST=London, C=GB" -validity 365 -genkey -noprompt -storepass test1234 -keypas
s test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s kafka.example.com -certreq -file client-cert-file -noprompt -storepass test123
4 &&
==> default: openssl x509 -req -CA ca-cert -CAkey ca-key -in client-cert-file -o
ut client-cert-signed -days 365 -CAcreateserial -passin pass:test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s CARoot -import -file ca-cert -noprompt -storepass test1234 &&
==> default: keytool -keystore /etc/security/tls/kafka.client.keystore.jks -alia
s kafka.example.com -import -file client-cert-signed -noprompt -storepass test12
34
==> default:  returned 1 instead of one of [0]
==> default: Warning: /Stage[main]/Main/File[/var/lib/kafka]: Skipping because o
f failed dependencies
==> default: Warning: /Stage[main]/Main/File[/etc/kafka/zookeeper.properties]: S
kipping because of failed dependencies
==> default: Warning: /Stage[main]/Main/File[/usr/sbin/start-zk-and-kafka]: Skip
ping because of failed dependencies
==> default: Warning: /Stage[main]/Main/File[/etc/kafka/server.properties]: Skip
ping because of failed dependencies
==> default: Warning: /Stage[main]/Main/File[/etc/kafka/consumer_ssl.properties]
: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Main/File[/etc/kafka/producer_ssl.properties]
: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Motd/File[/etc/motd]: Skipping because of fai
led dependencies
==> default: Notice: /Stage[main]/Ssh::Client::Config/File[/etc/ssh/ssh_config]/
content: content changed '{md5}8bd2ab7fa2f80c1af4c1ff05f85f0035' to '{md5}6b6e96
8bce40150262b7ab85822e7c07'
==> default: Notice: /Stage[main]/Ssh::Client::Config/File[/etc/ssh/ssh_known_ho
sts]/ensure: created
==> default: Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_confi
g]/File[/etc/ssh/sshd_config]/content: content changed '{md5}c403041b877348718fc
5145a00bce908' to '{md5}eccd13ee4b463bf59bc4c0997a89dfb5'
==> default: Notice: /Stage[main]/Ssh::Server::Service/Service[sshd]: Triggered
'refresh' from 2 events
==> default: Notice: Applied catalog in 44.83 seconds

**Comment by ewencp** [comment]
@keyboardfann Given that there's something about `\r` in there, my guess would be its an issue with the way git is checking out files on Windows (I think it does automatic newline translation between platforms) and then being mapped into the Linux VM as is in a way that is incompatible with the shell in the VM. https://help.github.com/articles/dealing-with-line-endings/ has an explanation of how to configure this on a per-repository basis. Could you try adjusting those settings and re-running `vagrant up`?

**Comment by keyboardfann** [comment]
Dear @ewencp ,
    Thank you for the quick feedback, I clone the git repo from linux again and it work normal.
